// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package data

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (name, state)
VALUES ($1, $2) RETURNING id, name, state
`

type CreateOrderParams struct {
	Name  string
	State string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.Name, arg.State)
	var i Order
	err := row.Scan(&i.ID, &i.Name, &i.State)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, name, state
FROM orders
WHERE id = ($1)
`

func (q *Queries) GetOrder(ctx context.Context, id int32) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(&i.ID, &i.Name, &i.State)
	return i, err
}
