// Code generated by sqlc. DO NOT EDIT.

package data

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, state string) (Order, error)
	GetOrder(ctx context.Context, id int64) (Order, error)
	UpdateOrderState(ctx context.Context, arg UpdateOrderStateParams) error
}

var _ Querier = (*Queries)(nil)
